#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "flaresolverr"
name = "FlareSolverr"
description.en = "Proxy server to bypass Cloudflare protection"
description.fr = "Serveur proxy pour contourner la protection de Cloudflare"

version = "3.3.21 ~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
code = "https://github.com/FlareSolverr/FlareSolverr"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = ["amd64"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    #[install.path]
    #type = "path"
    #default = "/flaresolverr"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr_FR", "en_GB"]
    default = "fr_FR"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/FlareSolverr/FlareSolverr/releases/download/v3.3.21/flaresolverr_linux_x64.tar.gz"
    amd64.sha256 = "e6f34cfa8047561e5c11080cdb6515e71776b5c5bb4e391336972ccc7368c4d6"
    #in_subdir = true

    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
